default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Akmalnaiem@2501
  host: localhost

development:
  <<: *default
  database: property_hub_development

test:
  <<: *default
  database: property_hub_test

production:
  primary: &primary_production
    <<: *default
    database: property_hub_production
    username: property_hub
    password: <%= ENV["PROPERTY_HUB_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: property_hub_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: property_hub_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: property_hub_production_cable
    migrations_paths: db/cable_migrate