default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Akmalnaiem@2501
  host: localhost

development:
  <<: *default
  database: property_hub_development

test:
  <<: *default
  database: property_hub_test

production:
  url: <%= ENV["DATABASE_URL"] %>